# Generated by Django 5.2.17 on 2026-10-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduand',
            name='manually_edited',
            field=models.BooleanField(default=False, help_text='Entered or changed by hand. Later list uploads will not overwrite these records unless the ICT chief chooses to.'),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='dummy_removed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='records_skipped',
            field=models.PositiveIntegerField(default=0, help_text='Left alone because they were edited by hand.'),
        ),
        migrations.AlterField(
            model_name='graduand',
            name='is_dummy',
            field=models.BooleanField(default=False, help_text='True for demo records. They are removed automatically when the real list is uploaded.'),
        ),
    ]