"""
Django settings for graduation project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1"]),
)
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# Admin URL is configurable so it is not at the guessable /admin/
ADMIN_URL = env("ADMIN_URL", default="admin/")

INSTITUTION_NAME = env("INSTITUTION_NAME", default="Your Institution Name")

# Default graduation date shown on the eligibility page / used for dummy data
GRADUATION_DATE = env("GRADUATION_DATE", default="2026-11-11")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',
    'axes',
    'graduation_portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # must be last
]

ROOT_URLCONF = 'graduation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'graduation_portal.context_processors.portal',
            ],
        },
    },
]

WSGI_APPLICATION = 'graduation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ---------------------------------------------------------------------------
# Database: choose with DB_ENGINE=mysql | postgresql | sqlite
# ---------------------------------------------------------------------------
DB_ENGINE = env("DB_ENGINE", default="mysql").lower()

if DB_ENGINE == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    _backends = {
        "mysql": "django.db.backends.mysql",
        "postgresql": "django.db.backends.postgresql",
    }
    if DB_ENGINE not in _backends:
        raise ValueError("DB_ENGINE must be one of: mysql, postgresql, sqlite")

    DATABASES = {
        "default": {
            "ENGINE": _backends[DB_ENGINE],
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD", default=""),
            "HOST": env("DB_HOST", default="127.0.0.1"),
            "PORT": env("DB_PORT", default="3306" if DB_ENGINE == "mysql" else "5432"),
        }
    }

    if DB_ENGINE == "mysql":
        # Use PyMySQL as a drop-in replacement for mysqlclient.
        import pymysql

        pymysql.version_info = (2, 2, 1, "final", 0)
        pymysql.install_as_MySQLdb()
        DATABASES["default"]["OPTIONS"] = {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', "OPTIONS": {"min_length": 10}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 30 * 60          # auto-logout after 30 minutes
SESSION_SAVE_EVERY_REQUEST = True     # ...of inactivity
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ---------------------------------------------------------------------------
# Student lookup
# ---------------------------------------------------------------------------
# Admission numbers are 4-6 digits, e.g. 9876, 11300
ADMISSION_NO_PATTERN = r"\d{4,6}"

# Rate limiting per IP address. Generous on purpose: students share campus Wi-Fi.
LOOKUP_WINDOW_MINUTES = env.int("LOOKUP_WINDOW_MINUTES", default=10)
LOOKUP_MAX_NOT_FOUND = env.int("LOOKUP_MAX_NOT_FOUND", default=15)
LOOKUP_MAX_TOTAL = env.int("LOOKUP_MAX_TOTAL", default=60)

# Only True when running behind a reverse proxy you control (nginx, etc.)
TRUST_PROXY_HEADERS = env.bool("TRUST_PROXY_HEADERS", default=False)

# CAPTCHA: simple maths question, easier on phones than distorted letters
CAPTCHA_CHALLENGE_FUNCT = "captcha.helpers.math_challenge"
CAPTCHA_TIMEOUT = 10  # minutes
CAPTCHA_IMAGE_SIZE = (180, 64)
CAPTCHA_FONT_SIZE = 38
CAPTCHA_NOISE_FUNCTIONS = ("captcha.helpers.noise_dots",)  # no lines through the digits
CAPTCHA_BACKGROUND_COLOR = "#f2f4f8"
CAPTCHA_FOREGROUND_COLOR = "#1b2a49"
CAPTCHA_TEST_MODE = False  # tests switch this on

# ---------------------------------------------------------------------------
# Admin login protection (django-axes)
# ---------------------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]
AXES_FAILURE_LIMIT = env.int("LOGIN_MAX_FAILURES", default=5)
AXES_COOLOFF_TIME = timedelta(minutes=env.int("LOGIN_LOCKOUT_MINUTES", default=60))
# Lock the IP + username pair, so a stranger cannot lock the real ICT chief out
# from the ICT chief's own connection.
AXES_LOCKOUT_PARAMETERS = [["ip_address", "username"]]
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = "graduation/locked_out.html"
if TRUST_PROXY_HEADERS:
    AXES_IPWARE_PROXY_COUNT = 1
    AXES_IPWARE_META_PRECEDENCE_ORDER = ("HTTP_X_FORWARDED_FOR", "REMOTE_ADDR")

